name: Test

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ALGO: shaderobotics/resnet
    container: shaderobotics/resnet:rolling-18
    steps:
      - run: curl https://raw.githubusercontent.com/open-shade/algos/main/tests/run_tests.sh --output ./run_tests.sh
      - run: chmod +x ./run.sh && ./run_tests.sh $ALGO
